name: Construcción

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Test Azure Registry
        uses: azure/docker-login@v1
        with:
          login-server: testdv2.azurecr.io
          username: ${{ secrets.USER_TEST }}
          password: ${{ secrets.PASSWORD_TEST }}

      - name: Push to Test Azure Registry
        run: |
          docker build . -t testdv2.azurecr.io/test:latest
          docker push testdv2.azurecr.io/test:latest
