name: Pruebas

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install bc
      run: |
        sudo apt-get update
        sudo apt-get install -y bc

    - name: Run tests
      run: npm run test --coverage

    - name: Check coverage
      run: |
        COVERAGE=$(npx jest --coverage --coverageReporters="text" | grep -o 'All files.*\([0-9\.]*\)' | grep -o '[0-9\.]*')
        echo "Total coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 40" | bc -l) )); then
          echo "Coverage is below 40%"
          exit 1
        fi